"""
acquisition/reporting/formatter.py — Format weekly reports as markdown.

Generates clean, readable markdown reports with tables, metrics,
and actionable insights.
"""
from .stats_collector import WeeklyStats
from .insight_generator import Insight


def delta_str(current: float, previous: float, pct: bool = False) -> str:
    """
    Format a delta between current and previous value.

    Args:
        current: Current value
        previous: Previous value
        pct: If True, values are percentages (0-1 range)

    Returns:
        Formatted string like "+15%" or "-3"
    """
    if previous == 0:
        if current == 0:
            return "—"
        return f"+{current:.0%}" if pct else f"+{current}"

    delta = current - previous
    if pct:
        # For percentage changes, show absolute percentage point change
        delta_pct = delta * 100  # Convert to percentage points
        sign = "+" if delta_pct > 0 else ""
        return f"{sign}{delta_pct:.1f}pp"
    else:
        # For absolute numbers
        delta_pct_change = (delta / previous) * 100
        sign = "+" if delta > 0 else ""
        return f"{sign}{delta} ({sign}{delta_pct_change:.0f}%)"


def format_markdown(stats: WeeklyStats, insights: list[Insight]) -> str:
    """
    Format complete weekly report as markdown.

    Args:
        stats: Weekly statistics
        insights: List of insights generated from the stats

    Returns:
        Formatted markdown report
    """
    # Calculate totals
    total_outreach = stats.dms_sent + stats.emails_sent

    # Format week dates
    week_str = f"{stats.week_start.strftime('%b %d')}–{stats.week_end.strftime('%b %d, %Y')}"

    # Build variant summary
    variant_summary = "N/A"
    if stats.variant_stats:
        best = stats.variant_stats[0]
        variant_summary = f"{best.get('name', 'Unknown')} ({best.get('reply_rate', 0):.1%} reply, {best.get('sends', 0)} sends)"

    # Build insights section
    insights_md = ""
    if insights:
        insights_md = "\n".join([
            f"{i+1}. **{ins.observation}**\n"
            f"   - Evidence: {ins.evidence}\n"
            f"   - → Action: {ins.recommended_action}\n"
            f"   - Confidence: {ins.confidence}%"
            for i, ins in enumerate(insights)
        ])
    else:
        insights_md = "No insights generated (insufficient data or analysis pending)."

    # Build pipeline snapshot summary
    pipeline_items = [f"**{k}**: {v}" for k, v in stats.pipeline_snapshot.items() if v > 0]
    pipeline_summary = " | ".join(pipeline_items) if pipeline_items else "Pipeline empty"

    report = f"""# Acquisition Pipeline — Week of {week_str}

## 📊 Funnel This Week

| Metric | This Week | vs Last Week |
|--------|-----------|--------------|
| **Discovered** | {stats.discovered} | {delta_str(stats.discovered, stats.prev_discovered)} |
| **Qualified** | {stats.qualified} ({stats.qualify_rate:.0%}) | {delta_str(stats.qualify_rate, stats.prev_qualify_rate, pct=True)} |
| **Warmup Sent** | {stats.warmup_sent} | — |
| **DMs Sent** | {stats.dms_sent} | — |
| **Emails Sent** | {stats.emails_sent} | — |
| **Total Outreach** | {total_outreach} | — |
| **Replies** | {stats.replies_received} ({stats.reply_rate:.1%} reply rate) | {delta_str(stats.reply_rate, stats.prev_reply_rate, pct=True)} |
| **Calls Booked** | {stats.calls_booked} | — |
| **Closed Won** | {stats.closed_won} | — |

## 📈 Conversion Rates

- **Discovery → Qualified**: {stats.qualify_rate:.1%}
- **Outreach → Reply**: {stats.reply_rate:.1%}
- **Email Reply Rate**: {stats.email_reply_rate:.1%}
- **Reply → Close**: {stats.close_rate:.1%}

## 🎯 Pipeline Snapshot (Current)

{pipeline_summary}

## 🏆 Best Performing

- **Platform**: {stats.top_platform}
- **Niche**: {stats.top_niche}
- **Message Variant**: {variant_summary}

## 💡 Insights & Recommended Actions

{insights_md}

---

*Generated by AAG Agent 10 — Pipeline Analytics & Reporting*
"""

    return report


def format_text_summary(stats: WeeklyStats) -> str:
    """
    Format a short text summary suitable for push notifications.

    Args:
        stats: Weekly statistics

    Returns:
        One-line summary string
    """
    return (
        f"{stats.replies_received} replies ({stats.reply_rate:.0%}), "
        f"{stats.calls_booked} calls, "
        f"{stats.closed_won} closed. "
        f"Top: {stats.top_platform}"
    )


def format_html(stats: WeeklyStats, insights: list[Insight]) -> str:
    """
    Format weekly report as HTML email.

    Args:
        stats: Weekly statistics
        insights: List of insights

    Returns:
        Formatted HTML report
    """
    # Calculate totals
    total_outreach = stats.dms_sent + stats.emails_sent
    week_str = f"{stats.week_start.strftime('%b %d')}–{stats.week_end.strftime('%b %d, %Y')}"

    # Build insights HTML
    insights_html = ""
    if insights:
        insights_items = "\n".join([
            f"""
            <li>
                <strong>{ins.observation}</strong><br>
                <em>Evidence:</em> {ins.evidence}<br>
                <em>→ Action:</em> {ins.recommended_action}<br>
                <small>Confidence: {ins.confidence}%</small>
            </li>
            """
            for ins in insights
        ])
        insights_html = f"<ul>{insights_items}</ul>"
    else:
        insights_html = "<p>No insights generated.</p>"

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }}
        h2 {{ color: #1e40af; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }}
        th {{ background-color: #f3f4f6; font-weight: 600; }}
        .metric {{ font-size: 24px; font-weight: bold; color: #2563eb; }}
        .delta-positive {{ color: #059669; }}
        .delta-negative {{ color: #dc2626; }}
        .insight-list {{ list-style: none; padding: 0; }}
        .insight-list li {{ margin: 15px 0; padding: 15px; background: #f9fafb; border-left: 4px solid #2563eb; }}
    </style>
</head>
<body>
    <h1>📊 Acquisition Pipeline — Week of {week_str}</h1>

    <h2>Funnel This Week</h2>
    <table>
        <tr><th>Metric</th><th>This Week</th><th>vs Last Week</th></tr>
        <tr><td>Discovered</td><td>{stats.discovered}</td><td>{delta_str(stats.discovered, stats.prev_discovered)}</td></tr>
        <tr><td>Qualified</td><td>{stats.qualified} ({stats.qualify_rate:.0%})</td><td>{delta_str(stats.qualify_rate, stats.prev_qualify_rate, pct=True)}</td></tr>
        <tr><td>Total Outreach</td><td>{total_outreach}</td><td>—</td></tr>
        <tr><td>Replies</td><td>{stats.replies_received} ({stats.reply_rate:.1%})</td><td>{delta_str(stats.reply_rate, stats.prev_reply_rate, pct=True)}</td></tr>
        <tr><td>Calls Booked</td><td>{stats.calls_booked}</td><td>—</td></tr>
        <tr><td>Closed Won</td><td>{stats.closed_won}</td><td>—</td></tr>
    </table>

    <h2>🏆 Best Performing</h2>
    <ul>
        <li><strong>Platform:</strong> {stats.top_platform}</li>
        <li><strong>Niche:</strong> {stats.top_niche}</li>
    </ul>

    <h2>💡 Insights & Recommended Actions</h2>
    {insights_html}

    <hr>
    <p><em>Generated by AAG Agent 10 — Pipeline Analytics & Reporting</em></p>
</body>
</html>
"""
    return html
