#!/usr/bin/env python3
"""Build a minimal private runtime environment without printing secret values."""

from __future__ import annotations

import argparse
import os
import shlex
from pathlib import Path

from dotenv import load_dotenv


ALLOWLIST = {
    "ANTHROPIC_API_KEY",
    "RATE_LIMIT_MAX",
    "RESEARCH_API_KEY",
    "SAFARI_AUTOMATION_WINDOW",
    "SAFARI_CONTROLLER_URL",
    "SAFARI_GATEWAY_URL",
    "SAFARI_RESEARCH_ENABLED",
    "SUPABASE_ANON_KEY",
    "SUPABASE_URL",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--runtime-base", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    runtime_base = args.runtime_base.expanduser().resolve()
    private_env = repo_root / ".env"
    if private_env.is_file():
        load_dotenv(private_env, override=False)

    values = {name: os.environ[name] for name in ALLOWLIST if os.environ.get(name)}
    values.update({
        "MARKET_RESEARCH_OUTPUT_DIR": str(runtime_base / "market-research-data"),
        "PORT": "3106",
        "RESEARCH_PORT": "3106",
    })

    lines = [
        "# Generated by build_market_research_runtime_env.py; chmod 600; never commit.",
        *(f"export {name}={shlex.quote(value)}" for name, value in sorted(values.items())),
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(args.output)
    args.output.chmod(0o600)
    print(f"Wrote {len(values)} allowlisted runtime variables to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
